### ISSUE TITLE
Update keyword names that changed in new version 

### ISSUE THREAD

**Issue by aparmendariz** [aparmendariz/mcf_docs#4]
Keywords from getting started: 
https://github.com/aparmendariz/mcf_docs/blob/27eea83c817133566aae2c143935c101d901d880/docs/source/getting_started.rst?plain=1#L217C1-L218C37

New keyword names:

https://github.com/aparmendariz/mcf_docs/blob/27eea83c817133566aae2c143935c101d901d880/docs/source/changelog.rst?plain=1#L87C1-L90C52

https://github.com/aparmendariz/mcf_docs/blob/27eea83c817133566aae2c143935c101d901d880/docs/source/changelog.rst?plain=1#L105C3-L110C1

**Comment by JFrischknecht** [comment]
Thanks for bringing this to my attention. 
Fixed with 27d160b
